version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9043:3000
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    restart: always